name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run check
      run: |
        python -m pip install --upgrade pip
        python -m pip install --user pipx pylint
        python -m pipx ensurepath
        pipx install poetry
        poetry update
        poetry install
        poetry run pyside6-project build
        poetry run pylint $(git ls-files '*.py')
