name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
      - name: Install pipx
        run: |
          python -m pip install --user pipx
          python -m pipx ensurepath
      - name: Install poetry
        run: |
          pipx install poetry
      - name: Install all dependencies
        run: |
          poetry install
      - name: Build Qt UI files to .py files
        run: |
          poetry run pyside6-project build
      - name: Lint .py files
        run: |
          poetry run pylint $(git ls-files '*.py')
